### ISSUE TITLE
Open app from link

### ISSUE THREAD

**Issue by Zeluok** [ldakhoa/GistHub#10]
The github app opens automatically when loading a guthub.com link. Can gisthub do this as well for gists?

**Comment by ldakhoa** [comment]
Hi, the GitHub app uses [Universal Link](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content) to automatically open iOS App.

Unfortunately, this requires a file to be uploaded to the website itself to redirect users to the native app, which means GistHub cannot do it unless GitHub add our App to the https://github.com/apple-app-site-association 😄

For the further plan, we might using JS Actions to attach Safari shortcut or integrate with https://www.opener.link, or use the redirect URL, for example gisthub.com/<username>/gist_id to open it by our app
