### ISSUE TITLE
Open gist using url scheme

### ISSUE THREAD

**Issue by Zeluok** [ldakhoa/GistHub#11]
Using shortcuts you can add a url opener to the ios share sheet. If setup correctly, you can send gist.github.com links to apps using url schemes.

Can we open gists using gisthub://https://gist.github.com/.../... ?

**Comment by ldakhoa** [comment]
Sure, we can definately do it by using JS Action, let me consider the solution to make it available.

**Comment by ldakhoa** [comment]
We can now open Gist from safari https://github.com/ldakhoa/GistHub/pull/32
