### ISSUE TITLE
GitHub Permissions

### ISSUE THREAD

**Issue by JadeDaniel** [ldakhoa/GistHub#54]
Hello! This looks great. I am hesitant to grant full repository access, however. I don't understand what gist management needs from my repositories. 

Thank you

**Comment by ldakhoa** [comment]
Hi, we use repository access for the `Report a Bug` feature. After a few tests, it just needs to grant public repo access. I will fix it and deploy it for the next version. Thank you a lot for giving me know.
 
<img width="433" alt="image" src="https://github.com/ldakhoa/GistHub/assets/39718754/df9e0c8a-797e-4ab2-9256-08b9cfe9be33">

**Comment by ldakhoa** [comment]
PR has raised at #56

**Comment by JadeDaniel** [comment]
Wow, quick turn around on this. Thank you very much!
